# Generated by Django 4.0 on 2022-01-02 15:59

import apps.product.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('images', models.JSONField(default=apps.product.models.image_dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('images', models.JSONField(default=apps.product.models.image_dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('images', models.JSONField(default=apps.product.models.image_dict)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('company', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(blank=True, max_length=250, null=True)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('marked_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('images', models.JSONField(default=apps.product.models.image_dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_benifits', models.TextField(blank=True, null=True)),
                ('direction_of_usage', models.TextField(blank=True, null=True)),
                ('safety_information', models.TextField(blank=True, null=True)),
                ('other_information', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(max_length=250)),
                ('category', models.ManyToManyField(blank=True, to='product.Category')),
                ('subcategory', models.ManyToManyField(blank=True, to='product.SubCategory')),
            ],
        ),
    ]
