# Generated by Django 4.0 on 2021-12-16 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('image', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('image', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('image', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('company', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(blank=True, max_length=250, null=True)),
                ('images', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_benifits', models.TextField(blank=True, null=True)),
                ('direction_of_usage', models.TextField(blank=True, null=True)),
                ('safety_information', models.TextField(blank=True, null=True)),
                ('other_information', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='product.Category')),
                ('subcategory', models.ManyToManyField(to='product.SubCategory')),
            ],
        ),
    ]
