# Generated by Django 4.0 on 2021-12-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='brand',
            name='images',
            field=models.JSONField(default={'main': '', 'other': []}),
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.JSONField(default={'main': '', 'other': []}),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='images',
            field=models.JSONField(default={'main': '', 'other': []}),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(default={'main': '', 'other': []}),
        ),
    ]
