# Generated by Django 4.0 on 2022-01-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breadth',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=50),
            preserve_default=False,
        ),
    ]
