# Generated by Django 4.0 on 2021-12-18 02:17

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_brand_image_remove_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='images',
            field=models.JSONField(default=apps.product.models.image_dict),
        ),
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.JSONField(default=apps.product.models.image_dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(default=apps.product.models.image_dict),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='images',
            field=models.JSONField(default=apps.product.models.image_dict),
        ),
    ]
