# Generated by Django 4.0 on 2021-12-22 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(default='AAAABBB12233', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=30),
            preserve_default=False,
        ),
    ]
