# Generated by Django 4.0 on 2022-01-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cod',
            field=models.BooleanField(default=False),
        ),
    ]
