# Generated by Django 4.0 on 2021-12-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='maximum_discount',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
