# Generated by Django 4.0 on 2021-12-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_batch_number_product_expiry_date_and_more'),
        ('shop', '0004_promocode_maximum_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='category',
            field=models.ManyToManyField(blank=True, to='product.Category'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='product.SubCategory'),
        ),
    ]
