# Generated by Django 4.0 on 2021-12-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_promocode_category_alter_promocode_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address2',
        ),
    ]
