# Generated by Django 4.0 on 2022-01-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiprockettoken',
            name='token',
            field=models.CharField(default='token', max_length=500),
        ),
    ]
